#ifndef UART_PLATFORM_SPECIFIC
#define UART_PLATFORM_SPECIFIC

#include "error_handling.h"
#include <stdint.h>
#include <stddef.h>

typedef enum {
    UART_PERIPHERAL_0,
    UART_PERIPHERAL_1
} uart_peripheral_inst_t;

typedef enum {
    UART_EXTRA_OPT_USE_DEFAULT,
    UART_EXTRA_OPT_MSB_FIRST = 1073741824,
    UART_EXTRA_OPT_INVERSE_CLOCK_POLARITY = 536870912,
    UART_EXTRA_OPT_SYNCHRONOUS_COMMUNICATION = 268435456,
    UART_EXTRA_OPT_AUTO_BAUD  = 67108864,
    UART_EXTRA_OPT_PARITY = 16777216,
    UART_EXTRA_OPT_OVERSAMPL_3X_ARITH = 1024,
    UART_EXTRA_OPT_OVERSAMPL_8X_FRACT = 768,
    UART_EXTRA_OPT_OVERSAMPL_8X_ARITH = 512,
    UART_EXTRA_OPT_OVERSAMPL_16X_FRACT = 256,
    UART_EXTRA_OPT_EXTERNAL_CLOCK = 128,
    UART_EXTRA_OPT_ENABLE_RX = 64,
    UART_EXTRA_OPT_IRDA_ENCODING = 32,
    UART_EXTRA_OPT_COLLISION_DETECT = 16,
    UART_EXTRA_OPT_TWO_STOP_BITS = 8,
    UART_EXTRA_OPT_CHAR_SIZE_5_BITS = 5,
    UART_EXTRA_OPT_CHAR_SIZE_6_BITS = 6,
    UART_EXTRA_OPT_CHAR_SIZE_7_BITS = 7,
    UART_EXTRA_OPT_CHAR_SIZE_9_BITS = 1,
} uart_extra_config_opt_t;

typedef enum {
    UART_CLK_SOURCE_USE_DEFAULT = 0x00
} uart_clock_sources_t;

#endif /* UART_PLATFORM_SPECIFIC */